# Generated by Django 4.2.6 on 2023-10-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rua', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='casa',
            new_name='habitante',
        ),
    ]
